### ISSUE TITLE
Unable to cd into buckets with spaces

### ISSUE THREAD

**Issue by bep** [muesli/thunder#1]
Very useful tool.

One little thing: I don't seem to be able to `cd` into buckets with spaces in the name. Which I maybe could fix on the db level, but let's say this is a legacy bolt db.

**Comment by muesli** [comment]
You should be able to `cd` into them just fine, but you need to escape the name with quotes, like:

`cd "foo bar"`

Let me know if that works for you. The auto completion still needs to handle that correctly, though.

**Comment by bep** [comment]
You are right ... What I tried to `cd` into was a value and not a bucket, so I got this message:

```
Unable to change to bucket ***
```

It would be cool if you somehow could indicate that it is a bucket or not in the listing.

**Comment by muesli** [comment]
Changed the error handling a bit and implemented your suggestion: get-ing buckets and cd-ing values now throws appropriate errors.

Upstream completion issue here: https://github.com/abiosoft/ishell/issues/52
